### ISSUE TITLE
Add aliasing information to the spreadsheet

### ISSUE THREAD

**Issue by groppcw** [edponce/DoyleInvestigators#15]
Specifically; how is Jefferson Hope referred to before his name is revealed? (Taxi driver? Cabby?)

**Comment by groppcw** [comment]
Interestingly, the word "cab" is used interchangeably to refer to the driver and the vehicle itself. "Cabman" is more specific but less frequently used. However, given the circumstances, it is reasonable to assume that whenever either of these (or "hansom", a type of carriage, albeit a different one than the murderer used) is used, it is in reference to someone driving one, either directly or indirectly, so I think these words will suffice for our purposes.

I've added the words "cab" and "cabman" to the spreadsheet as aliases for Jefferson Hope; most usage of the words in the story alludes to him or his actions.

**Comment by edponce** [comment]
I agree with your train of thought. By the way, this is good observation to make note in the document. There are difficulties when working with aliases, moreover, when aliases may also refer to a common object (e.g., cab). It seems that in order to be able to distinguish between referencing a person or an object, context is required.
