### ISSUE TITLE
Identify regex

### ISSUE THREAD

**Issue by edponce** [edponce/DoyleInvestigators#3]
We need to build a set of regular expressions for finding names (characters can have aliases), places, etc.
For each entity we should have details of In what page, paragraph, novel part do they appear.

Pipeline:
* Split novel into parts/chapters (regex)
* Sentence segmentation for each chapter (regex)
* Tokenize each sentence (regex)
* Apply regular expressions (regex)

**Comment by edponce** [comment]
A caveat for identifying characters is that their names may appear because they are part of the current scene or they are being referred to by other characters. We need to differentiate these cases?
An approach is to consider names that only appear between quotes for a given part as "being referred to".

**Comment by fabianfallasmoya** [comment]
I'll start with 'Split novel into parts/chapters (manually or regex)'. I hope to have this by tomorrow. 

Btw, using github to collaborate looks pretty cool. I think we don't need to use slack. Just one question: does github will send me a notification in my email? for example when you reply to this, or when somebody tags my username.

**Comment by edponce** [comment]
Some novels are broken into parts and then chapters. Note that part and chapter titles have a fixed form so you can split with a regex. For example, "Part 1...." and "Chapter I...". Similarly, you can trim the text that appears before part 1 and text that appears after the novel's end. You should place the novel files in Google Drive and read them from the Colab notebook (or something like that).

@fabianfallasmoya You will get notification emails related to issues for the following cases:
* Replies to an issue that you authored/created
* If you are mentioned/tagged in a message
* Replies to an issue you were assigned

**Comment by fabianfallasmoya** [comment]
@edponce I just finished with the task "Split novel into parts/chapters (manually or regex)". The code is in colab. I created a dictionary of dictionaries (parts->chapters->list_of_texts)... not sure if this is the best way, this is my first time doing this :)
I can change it if necessary. 

I tried to write comments in the code, and tried to let it very simple.

I can move on to the next task "Sentence segmentation for each chapter (spaCy)". I saw the code for this in spaCy. Can you briefly explain to me the idea/purpose of doing this? 

btw, I read the text by using the url, so that we don't need to copy files into drive.

**Comment by edponce** [comment]
@fabianfallasmoya Great! It is perfectly fine to get the text directly from Gutenberg's URL.
Based on assignment description, we should only use regex for all text processing. We can use spaCy for comparisons later on, but we will do this if time permits. If we are to use spaCy, I would suggest that I would do it, given that I know spaCy fairly well.

I will take a look at the Colab notebook tonight and provide feedback if necessary.
For sentence splitting, consider constructing a regex that takes into account end-of-sentence punctuation marks. There will be exceptions that we can handle explicitly, for example, in "Mr. Holmes" you do not want to split in the period.
The sentence splitting should apply to all the novels, that is, it is not novel-specific.

**Comment by edponce** [comment]
@fabianfallasmoya Remember that we need to store the global text index of each part, chapter, sentence, etc. You should get this index from the results returned from **re.match** using the **starts()** and **ends()** methods.

**Comment by fabianfallasmoya** [comment]
@edponce thanks for the hints. One question: Does the global index will be related to the original text?
for example, the original text including (the one that includes 'metadata' from The Project Gutenberg). Actually, that is not difficult, but it will change slightly my code because the first task I do is to trim the text to get rid of the 'metadata'.

I just want to make sure before I change the code.

**Comment by edponce** [comment]
@fabianfallasmoya The global index should be considered from the original text that is downloaded. I am reviewing the code you made and I am making some changes. I am thinking of a good data structure that will allow us to store processing output effectively. I will get back to you later today. We can also have a quick discussion in tonight's meeting.

**Comment by fabianfallasmoya** [comment]
Thanks, @edponce! I just realized that the code is tailored for one novel (THE VALLEY OF FEAR), but it will not work for the rest of the novels. I thought everything in The Project Gutenberg followed the same pattern, but it changes from one book to another.

Some things I have found:

- The **match** function is not very useful since it will stop in the first **\n.** That's why I use the function **search**, instead.
- The **search** will stop as soon as it finds the first match. That's why I use the function **split** in some cases.

**Comment by edponce** [comment]
Yes, you are correct on those observations. I am writing some regex that should work across Gutenberg's syntax.
